### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by CBielstein** [dkxce/AFSK1200Modem#1]
Howdy! I'm interested in potentially reusing some or all of this code in some APRS tinkering I'm doing. I don't want to trample your intellectual property rights. I'm curious if you'd be okay with code reuse like that. If you'd consider adding an open source license that allows reuse (MIT, GPL, Apache, etc.), that'd be even better to ensure everything is on the up and up.

Thanks for considering!

**Comment by dkxce** [comment]
Hello @CBielstein. Sorry for longtime answer. You can use source code in your projects as you wish. If you will publish sources of your projects anywhere just indicate original source.

**Comment by dkxce** [comment]
Hello @CBielstein. Sorry for longtime answer. You can use source code in any your projects as you with. Just  indicate the original source if you will publish source code of they anywhere.

**Comment by CBielstein** [comment]
Thanks! I'll certainly attribute and let you know if I end up using the code in anything. 😊
